import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:phosphor_flutter/phosphor_flutter.dart';
import 'package:go_router/go_router.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:url_launcher/url_launcher.dart';
import '../../../../core/presentation/widgets/aesthetic_background.dart';
import '../../../../core/services/ai_service.dart';
import '../../../../core/services/app_prefs.dart';
import '../../../../core/models/user_criteria.dart';

class RecommendationsScreen extends ConsumerStatefulWidget {
  const RecommendationsScreen({super.key});

  @override
  ConsumerState<RecommendationsScreen> createState() => _RecommendationsScreenState();
}

class _RecommendationsScreenState extends ConsumerState<RecommendationsScreen> {
  List<Map<String, dynamic>> _recommendations = [];
  bool _isLoading = true;
  String? _errorMessage;
  String _weeklyFocus = "Discover Your AI Picks";

  @override
  void initState() {
    super.initState();
    _fetchRecommendations();
  }

  Future<void> _fetchRecommendations() async {
    setState(() => _isLoading = true);
    try {
      final user = FirebaseAuth.instance.currentUser;
      if (user != null) {
        final snap = await FirebaseFirestore.instance
            .collection('users')
            .doc(user.uid)
            .collection('weeklyRecommendations')
            .get();

        if (snap.docs.isNotEmpty) {
          final docs = snap.docs.toList();
          docs.sort((a, b) {
            final ta = a.get('generatedAt') as Timestamp?;
            final tb = b.get('generatedAt') as Timestamp?;
            if (ta == null || tb == null) return 0;
            return tb.compareTo(ta);
          });

          DocumentSnapshot? bestDoc;
          for (var doc in docs) {
            final data = doc.data() as Map<String, dynamic>;
            final items = (data['picks'] ?? data['recommendations'] ?? data['suggestions'] ?? data['resources']) as List<dynamic>? ?? [];
            if (items.isNotEmpty) {
              bestDoc = doc;
              break;
            }
          }

          final docToUse = bestDoc ?? docs.first;
          final data = docToUse.data() as Map<String, dynamic>;
          final itemsList = (data['picks'] ?? data['recommendations'] ?? data['suggestions'] ?? data['resources']) as List<dynamic>? ?? [];

          if (mounted) {
            setState(() {
              _weeklyFocus = data['weeklyFocus'] ?? data['focus'] ?? data['title'] ?? "Discover Your AI Picks";
              _recommendations = List<Map<String, dynamic>>.from(itemsList);
            });
          }
        } else {
          await _generateOnDemand(user.uid);
        }
      }
    } catch (e) {
      debugPrint("Error fetching recommendations: $e");
      setState(() => _errorMessage = "Analysis Sync Error: $e");
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  Future<void> _generateOnDemand(String uid) async {
    setState(() => _errorMessage = null);
    try {
      final criteria = await AppPrefs.loadCriteria() ?? UserCriteria(
        careerGoal: "Professional Tech Growth",
        experienceLevel: "Beginner",
        weeklyHours: 10,
      );

      debugPrint("Generating recommendations for: ${criteria.careerGoal}");
      final result = await AIService.generateRecommendations(criteria);
      debugPrint("Generation successful!");
      
      final now = DateTime.now();
      final weekId = "week_${now.year}_${now.month}_${(now.day / 7).ceil()}";
      
      await FirebaseFirestore.instance
          .collection('users').doc(uid)
          .collection('weeklyRecommendations')
          .doc(weekId)
          .set({
            ...result,
            'generatedAt': FieldValue.serverTimestamp(),
            'weekId': weekId,
            'isAutoGenerated': true,
          }, SetOptions(merge: true));

      if (mounted) {
        setState(() {
          _weeklyFocus = result['weeklyFocus'] ?? "Your Personal AI Picks";
          _recommendations = List<Map<String, dynamic>>.from(result['picks'] ?? []);
          _errorMessage = null;
        });
      }
    } catch (e) {
      debugPrint("Failed to generate recommendations: $e");
      if (mounted) {
        setState(() => _errorMessage = "AI Generation Failed: $e");
      }
    }
  }

  Future<void> _launchUrl(String url) async {
    if (url.isEmpty) return;
    
    // Auto-fix missing protocol
    String processedUrl = url.trim();
    if (!processedUrl.startsWith('http://') && !processedUrl.startsWith('https://')) {
      processedUrl = 'https://$processedUrl';
    }

    try {
      final uri = Uri.parse(processedUrl);
      // Launch directly without canLaunchUrl for better reliability on Android 30+ 
      // if queries are missing or incomplete. Android handles the intent error.
      await launchUrl(uri, mode: LaunchMode.externalApplication);
    } catch (e) {
      debugPrint("Could not launch $url: $e");
    }
  }

  void _handleSkip(int index) {
    setState(() {
      _recommendations.removeAt(index);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: AestheticBackground(
        child: Column(
          children: [
            _buildHeader(context),
            Expanded(
              child: _isLoading 
                ? Center(
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        const CircularProgressIndicator(color: Color(0xFF3B82F6)),
                        const SizedBox(height: 24),
                        Text(
                          "AI is generating your\npersonalized picks...",
                          textAlign: TextAlign.center,
                          style: GoogleFonts.poppins(
                            color: const Color(0xFF64748B),
                            fontSize: 15,
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ],
                    ),
                  )
                : _errorMessage != null
                  ? _buildErrorState()
                  : _recommendations.isEmpty
                    ? _buildEmptyState()
                    : SingleChildScrollView(
                      physics: const BouncingScrollPhysics(),
                      padding: const EdgeInsets.fromLTRB(24, 0, 24, 100),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          const SizedBox(height: 24),
                          _buildStatsRow(),
                          const SizedBox(height: 32),
                          _buildFocusBanner(_weeklyFocus),
                          const SizedBox(height: 32),
                          _buildPrioritySection('AI PICKS', const Color(0xFF3B82F6)),
                          const SizedBox(height: 16),
                          ..._recommendations.asMap().entries.map((entry) {
                            final idx = entry.key;
                            final pick = entry.value;
                            
                            // Robust field extraction
                            final skillName = pick['skill'] ?? pick['skillName'] ?? 'New Skill';
                            final resourceTitle = pick['resource'] ?? pick['title'] ?? 'Learning Resource';
                            final type = pick['type'] ?? 'Article';
                            final duration = pick['duration'] ?? '15 min';

                            return Padding(
                              padding: const EdgeInsets.only(bottom: 16),
                              child: _buildRecommendationCard(
                                idx,
                                skillName,
                                resourceTitle,
                                [
                                  skillName,
                                  type,
                                  duration
                                ],
                                pick['url'] ?? '',
                                _getIconForType(type),
                                _getColorForSkill(skillName),
                              ),
                            );
                          }),
                        ],
                      ),
                    ),
            ),
          ],
        ),
      ),
    );
  }

  IconData _getIconForType(String? type) {
    if (type == null) return PhosphorIcons.bookOpen(PhosphorIconsStyle.fill);
    final t = type.toLowerCase();
    if (t.contains('video')) return PhosphorIcons.videoCamera(PhosphorIconsStyle.fill);
    if (t.contains('doc') || t.contains('article')) return PhosphorIcons.article(PhosphorIconsStyle.fill);
    if (t.contains('course')) return PhosphorIcons.graduationCap(PhosphorIconsStyle.fill);
    if (t.contains('quiz')) return PhosphorIcons.trophy(PhosphorIconsStyle.fill);
    if (t.contains('practice')) return PhosphorIcons.code(PhosphorIconsStyle.fill);
    return PhosphorIcons.lightbulb(PhosphorIconsStyle.fill);
  }

  Color _getColorForSkill(String? skill) {
    final colors = [
      const Color(0xFF3B82F6),
      const Color(0xFF0EA5E9),
      const Color(0xFF8B5CF6),
      const Color(0xFF10B981),
      const Color(0xFFF59E0B),
    ];
    if (skill == null) return colors[0];
    return colors[skill.length % colors.length];
  }

  Widget _buildEmptyState() {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(PhosphorIcons.sparkle(), size: 64, color: Colors.grey[300]),
          const SizedBox(height: 16),
          Text(
            "No recommendations yet",
            style: GoogleFonts.poppins(color: Colors.grey[500], fontSize: 16),
          ),
          const SizedBox(height: 8),
          Text(
            "Complete some lessons to get AI tips!",
            style: GoogleFonts.poppins(color: Colors.grey[400], fontSize: 13),
          ),
          const SizedBox(height: 24),
          ElevatedButton.icon(
            onPressed: _fetchRecommendations,
            icon: Icon(PhosphorIcons.arrowsClockwise()),
            label: Text("Retry Generation"),
            style: ElevatedButton.styleFrom(
              backgroundColor: const Color(0xFF3B82F6),
              foregroundColor: Colors.white,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildErrorState() {
    return Center(
      child: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 40),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Container(
              padding: const EdgeInsets.all(20),
              decoration: BoxDecoration(
                color: Colors.red[50],
                shape: BoxShape.circle,
              ),
              child: Icon(PhosphorIcons.warningCircle(), size: 48, color: Colors.red[400]),
            ),
            const SizedBox(height: 24),
            Text(
              "Something went wrong",
              style: GoogleFonts.poppins(
                fontWeight: FontWeight.bold,
                fontSize: 18,
                color: const Color(0xFF0F172A),
              ),
            ),
            const SizedBox(height: 8),
            Text(
              _errorMessage ?? "Unexpected system error",
              textAlign: TextAlign.center,
              style: GoogleFonts.poppins(color: Colors.grey[600], fontSize: 13),
            ),
            const SizedBox(height: 32),
            SizedBox(
              width: 200,
              height: 50,
              child: ElevatedButton(
                onPressed: _fetchRecommendations,
                style: ElevatedButton.styleFrom(
                  backgroundColor: const Color(0xFF3B82F6),
                  foregroundColor: Colors.white,
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                ),
                child: Text("Retry", style: GoogleFonts.poppins(fontWeight: FontWeight.bold)),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildHeader(BuildContext context) {
    return SafeArea(
      child: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
        child: Row(
          children: [
            IconButton(
              icon: Icon(PhosphorIcons.caretLeft(), color: const Color(0xFF1E293B)),
              onPressed: () => context.pop(),
            ),
            const SizedBox(width: 8),
            Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'AI RECOMMENDATIONS',
                  style: GoogleFonts.orbitron(
                    fontSize: 16,
                    fontWeight: FontWeight.bold,
                    color: const Color(0xFF1E293B),
                    letterSpacing: 1.5,
                  ),
                ),
                Text(
                  'Personalized resources for you',
                  style: GoogleFonts.poppins(
                    fontSize: 11,
                    color: const Color(0xFF64748B),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildStatsRow() {
    return Row(
      children: [
        Expanded(child: _buildStatItem('${_recommendations.length}', 'Total', const Color(0xFF3B82F6))),
        const SizedBox(width: 12),
        Expanded(child: _buildStatItem('${_recommendations.where((r) => (r['priority'] ?? '') == 'High').length}', 'High Priority', const Color(0xFFEF4444))),
        const SizedBox(width: 12),
        Expanded(child: _buildStatItem('~2h', 'Est. Time', const Color(0xFF10B981))),
      ],
    );
  }

  Widget _buildStatItem(String value, String label, Color color) {
    return Container(
      padding: const EdgeInsets.symmetric(vertical: 20, horizontal: 12),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: const Color(0xFFF1F5F9)),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.02),
            blurRadius: 10,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        children: [
          Text(
            value,
            style: GoogleFonts.orbitron(
              fontSize: 18,
              fontWeight: FontWeight.bold,
              color: color,
            ),
          ),
          const SizedBox(height: 4),
          Text(
            label,
            textAlign: TextAlign.center,
            style: GoogleFonts.poppins(
              fontSize: 10,
              color: const Color(0xFF94A3B8),
              fontWeight: FontWeight.w500,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildFocusBanner(String focus) {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: const Color(0xFFEFF6FF),
        borderRadius: BorderRadius.circular(24),
        border: Border.all(color: const Color(0xFFDBEAFE)),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Container(
            padding: const EdgeInsets.all(10),
            decoration: BoxDecoration(
              color: const Color(0xFF3B82F6),
              borderRadius: BorderRadius.circular(12),
            ),
            child: Icon(PhosphorIcons.sparkle(PhosphorIconsStyle.fill), color: Colors.white, size: 20),
          ),
          const SizedBox(width: 16),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  "THIS WEEK'S FOCUS",
                  style: GoogleFonts.orbitron(
                    fontWeight: FontWeight.bold,
                    fontSize: 12,
                    color: const Color(0xFF1E3A8A),
                    letterSpacing: 1,
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  focus,
                  style: GoogleFonts.poppins(
                    fontSize: 12,
                    color: const Color(0xFF1E40AF),
                    height: 1.5,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildPrioritySection(String title, Color color) {
    return Row(
      children: [
        Container(
          width: 8,
          height: 8,
          decoration: BoxDecoration(color: color, shape: BoxShape.circle),
        ),
        const SizedBox(width: 8),
        Text(
          title.toUpperCase(),
          style: GoogleFonts.orbitron(
            fontSize: 14,
            fontWeight: FontWeight.bold,
            color: const Color(0xFF0F172A),
            letterSpacing: 1,
          ),
        ),
      ],
    );
  }

  Widget _buildRecommendationCard(
    int index,
    String title,
    String desc,
    List<String> tags,
    String url,
    IconData icon,
    Color iconColor,
  ) {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(24),
        border: Border.all(color: const Color(0xFFF1F5F9)),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.02),
            blurRadius: 10,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Container(
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(
                  color: iconColor.withOpacity(0.1),
                  borderRadius: BorderRadius.circular(14),
                ),
                child: Icon(icon, color: iconColor, size: 24),
              ),
              const SizedBox(width: 16),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      title.toUpperCase(),
                      style: GoogleFonts.orbitron(
                        fontWeight: FontWeight.bold,
                        fontSize: 13,
                        color: const Color(0xFF1E293B),
                        letterSpacing: 0.5,
                      ),
                    ),
                    const SizedBox(height: 4),
                    Text(
                      desc,
                      style: GoogleFonts.poppins(
                        fontSize: 12,
                        color: const Color(0xFF64748B),
                        height: 1.4,
                      ),
                    ),
                  ],
                ),
              ),
              IconButton(
                onPressed: () => _handleSkip(index),
                icon: Icon(PhosphorIcons.x()),
                color: const Color(0xFFCBD5E1),
                iconSize: 16,
              ),
            ],
          ),
          const SizedBox(height: 20),
          Row(
            children: tags.map((tag) {
              return Container(
                margin: const EdgeInsets.only(right: 8),
                padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                decoration: BoxDecoration(
                  color: const Color(0xFFF1F5F9),
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    if (tag == 'High' || tag == 'Med') ...[
                      Icon(PhosphorIcons.circle(PhosphorIconsStyle.fill), 
                           color: tag == 'High' ? const Color(0xFFEF4444) : const Color(0xFFF59E0B), 
                           size: 8),
                      const SizedBox(width: 4),
                    ],
                    if (tag.contains('min') || tag.contains('hour')) ...[
                      Icon(PhosphorIcons.clock(), color: const Color(0xFF64748B), size: 12),
                      const SizedBox(width: 4),
                    ],
                    Text(
                      tag,
                      style: GoogleFonts.poppins(
                        fontSize: 10,
                        fontWeight: FontWeight.w600,
                        color: const Color(0xFF64748B),
                      ),
                    ),
                  ],
                ),
              );
            }).toList(),
          ),
          const SizedBox(height: 24),
          Row(
            children: [
              Expanded(
                child: SizedBox(
                   height: 44,
                   child: ElevatedButton(
                    onPressed: url.isEmpty ? null : () => _launchUrl(url),
                    style: ElevatedButton.styleFrom(
                      backgroundColor: const Color(0xFF3B82F6),
                      foregroundColor: Colors.white,
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                      disabledBackgroundColor: Colors.grey[300],
                      elevation: 0,
                    ),
                    child: Text('Start Learning', style: GoogleFonts.poppins(fontWeight: FontWeight.w600, fontSize: 13)),
                  ),
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: SizedBox(
                  height: 44,
                  child: OutlinedButton(
                    onPressed: () => _handleSkip(index),
                    style: OutlinedButton.styleFrom(
                      side: const BorderSide(color: Color(0xFFE2E8F0)),
                      foregroundColor: const Color(0xFF64748B),
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                    ),
                    child: Text('Skip', style: GoogleFonts.poppins(fontWeight: FontWeight.w600, fontSize: 13)),
                  ),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}
